name: Deploy to Azure Spring Apps
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload Artifcat for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-example
          path: build/libs/*.jar
  deploy:
    runs-on: buntu-latest
    needs: build
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: spring-boot-example
      - name: Deploy to Azure App Service
        uses: azure/webapp-deploy@v2
        with:
          app-name: spring-boot-web
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: build/libs/demo-0.0.1-SNAPSHOT.jar